### ISSUE TITLE
USER STORY: HOME PAGE : Check Future Classes

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_4#8]
# DESCRIPTION
As a **Site User** I can **view a list of future classes** so that **I can register on it**

# ACCEPTANCE CRITERIA
1. View a list of future classes on the home page
2. Criteria2
3. Criteria3

# TASKS
- [ ] Create Classes app
- [ ] Create Classes db
- [ ] Shown classes on the home page
