### ISSUE TITLE
USER STORY: HOME PAGE : Rental Availability

### ISSUE THREAD

**Issue by arthurmezaonik** [arthurmezaonik/portfolio_project_4#9]
#DESCRIPTION
As a **Site User** I can **check available days and times to rent** so that **I can choose the better day for me**

#ACCEPTANCE CRITERIA
1. Be able to check rental availability on the home page

#TASKS
- [ ] Create booking app
- [ ] Create booking db
- [ ] Display fields to be booked on the home page
